// <auto-generated />
using System;
using Index.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Index.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210624142356_Seed_Initial")]
    partial class Seed_Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Index.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1496eac-178b-4b61-aca5-1aecd141ac1e"),
                            Content = "hey Pesho",
                            CreatedOn = new DateTime(2021, 6, 24, 17, 23, 56, 587, DateTimeKind.Local).AddTicks(6128),
                            User = "gosho'"
                        },
                        new
                        {
                            Id = new Guid("9f332bd2-fad5-4c16-8bef-f04e50034727"),
                            Content = "hey Gosho",
                            CreatedOn = new DateTime(2021, 6, 24, 17, 23, 56, 589, DateTimeKind.Local).AddTicks(3994),
                            User = "pesho'"
                        },
                        new
                        {
                            Id = new Guid("4fae6b97-83a6-4628-910e-3522058540b3"),
                            Content = "What's up?",
                            CreatedOn = new DateTime(2021, 6, 24, 17, 23, 56, 589, DateTimeKind.Local).AddTicks(4021),
                            User = "gosho'"
                        },
                        new
                        {
                            Id = new Guid("01f01d21-018e-4ddb-9a2b-c20352f1a8e1"),
                            Content = "Nothing",
                            CreatedOn = new DateTime(2021, 6, 24, 17, 23, 56, 589, DateTimeKind.Local).AddTicks(4026),
                            User = "pesho'"
                        },
                        new
                        {
                            Id = new Guid("25543851-b6ec-49e6-9e37-cf0eb3df4f2e"),
                            Content = "How are you?",
                            CreatedOn = new DateTime(2021, 6, 24, 17, 23, 56, 589, DateTimeKind.Local).AddTicks(4036),
                            User = "gosho'"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
